### ISSUE TITLE
Bug in STARFISH annotate code

### ISSUE THREAD

**Issue by drdna** [egluckthaler/starfish#11]
There is a bug in the code that is preventing execution of the bedtools intersect command:

[Mon Aug  5 21:10:14 2024] checking formatting of GFFs in ome2gff.txt..
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `bedtools intersect -a CD156_SF_starships/CD156.filt.gff -b <(grep -w mRNA /scratch/farman/STARFISH/CD156_processed.gff) -wao >> CD156_SF_starships/CD156.intersect.gff'

[Mon Aug  5 21:10:14 2024] error: could not execute bedtools intersect on commandline for CD156_SF_starships/CD156.filt.gff and /scratch/farman/STARFISH/CD156_processed.gff, exiting..
No such file or directory

Troubleshooting is complicated by the fact that the error message is incorrect. Both files referenced in the message are present and correct in the specified locations. However, bedtools intersect is looking for a temp.gff that, apparently, is never created.

Note: This step also fails with the starfish **examples** datasets.

**Comment by egluckthaler** [comment]
Not sure I was able to completely reproduce this bug because starfish annotate works with the example data for me, but I added sanity checks that will provide more details for troubleshooting. let me know if it works for you
