### ISSUE TITLE
[question] do gene names have to be unique?

### ISSUE THREAD

**Issue by JWDebler** [egluckthaler/starfish#15]
Hi team,

I just annotated a bunch of genomes quickly with funannotate and realised after eggnog annotation that all the gene names accross all genomes are FUN_00001 etc. Is that a problem? After converting the eggnog output into orthogroups there won't a away to assign the gene names back to isolates.

Just wondering if that is going to be a problem for the pipeline and if I should go and rename all my genes :-)
Cheers,
Johannes

**Comment by egluckthaler** [comment]
Hi Johannes, yes that will be a problem. All contigs and genes must be formatted as follows: 
```<genomeID><separator><uniqueIdentifier>```
See the formatting requirements section in the manual for more info
