### ISSUE TITLE
typo in install instructions

### ISSUE THREAD

**Issue by BenAuxier** [egluckthaler/starfish#3]
From: https://github.com/egluckthaler/starfish/wiki/Installation

when replacing the cnef.cc file, your instructions say:
`cp ../scripts/cneff.cc .`

but it should say:
`cp ../scripts/cnef.cc .`

I guess this is a bit of a dangerous error, and might pop up due to other install errors. Since the original file and the new file have the same names, it is hard to distinguish between them. 

I guess an option would be to rename your cnef.cc to cnef_starfish.cc

and then add a sed command for the Makefile? Something like this?
`sed -i "s/cnef.cc/cnef_starfish.cc/"` Makefile

**Comment by egluckthaler** [comment]
thanks for catching that Ben and good suggestion, I fixed the wiki. For now, before I test it, I'm going to leave the filename as is and advise users to remove the original file before copying the modified one over.
