### ISSUE TITLE
Typo in step-by-step tutorial

### ISSUE THREAD

**Issue by Rowena-h** [egluckthaler/starfish#4]
I believe that the annotate command in the [step-by-step tutorial](https://github.com/egluckthaler/starfish/wiki/Step-by-step-tutorial) has a typo:

`starfish annotate -T 2 -x macpha6_tyr -a ome2assembly.txt -g macpha6.gff3 -p ../database/YRsuperfams.p1-512.hmm -P ../database/YRsuperfamRefs.faa -i tyr -o geneFinder/`

Where the `-g` parameter should be `ome2gff.txt` instead of `macpha6.gff3`.

Thanks for the fantastic programme!

**Comment by egluckthaler** [comment]
Fixed, thank you!
