### ISSUE TITLE
Trying to run on my own samples

### ISSUE THREAD

**Issue by tania-k** [egluckthaler/starfish#5]
Hello Emile and group! Excited to try your program on my Histoplasma datasets but I have hit a couple of snags, some I've solved but currently stuck on this one. 

I have been following your tutorial for your test dataset and the portion I have been stuck on is your eggnog annotation sorting. 
My genomes have been annotated using Funannotate, but I also attempted an eggnog-mapper run and my output does not look like yours.

Your step that cuts your emapper into a text file for later steps is giving me an issue:
>cut -f1,10 ann/*emapper.annotations | grep -v '#' | perl -pe 's/^([^\s]+?)\t([^\|]+).+$/\1\t\2/' > ann/macph6.gene2og.txt

the -f1,10 cut is looking for "bestOG|evalue|score" tab where it pulls out the first portion "bestOG" to create the text file. Is it maybe a -flag I am missing for this specific emapper output?

> Funannotate:
>GeneID	TranscriptID	Feature	Contig	Start	Stop	Strand	Name	Product	Alias/Synonyms	EC_number	BUSCO	PFAM	InterPro	EggNog	COG	GO Terms	Secreted	Membrane	Protease	CAZyme	Notes	gDNA	mRNA	CDS-transcript	Translation
19VMG-15_000001	19VMG-15_000001-T1	mRNA	scaffold_1	63793	65897	+		hypothetical protein		2.1.1.310	EOG091P0ENB	PF01189;PF17125	IPR001678 SAM-dependent methyltransferase RsmB-F/NOP2-type domain;IPR011023 Nop2p;IPR018314 Bacterial Fmu (Sun)/eukaryotic nucleolar NOL1/Nop2p, conserved site;IPR023267 RNA (C5-cytosine) methyltransferase;IPR023273 RNA (C5-cytosine) methyltransferase, NOP2;IPR029063 S-adenosyl-L-methionine-dependent methyltransferase superfamily;IPR031341 Ribosomal RNA small subunit methyltransferase F, N-terminal	ENOG503NUZ7	L:(L) Replication, recombination and repair	GO_component: GO:0005730 - nucleolus [Evidence IEA];GO_function: GO:0008757 - S-adenosylmethionine-dependent methyltransferase activity [Evidence IEA];GO_function: GO:0008168 - methyltransferase activity [Evidence IEA];GO_function: GO:0003723 - RNA binding [Evidence IEA];GO_function: GO:0009383 - rRNA (cytosine-C5-)-methyltransferase activity [Evidence IEA];GO_process: GO:0006396 - RNA processing [Evidence IEA];GO_process: GO:0001510 - RNA methylation [Evidence IEA];GO_process: GO:0070475 - rRNA base methylation [Evidence IEA];GO_process: GO:0000470 - maturation of LSU-rRNA [Evidence IEA]									 

> My eggnog-mapper:
> #query	seed_ortholog	evalue	score	eggNOG_OGs	max_annot_lvl	COG_category	Description	Preferred_name	GOs	EC	KEGG_ko	KEGG_PathwayKEGG_Module	KEGG_Reaction	KEGG_rclass	BRITE	KEGG_TC	CAZy	BiGG_Reaction	PFAMs
01_16_1	5037.XP_001538943.1	0	3312	COG1020@1|root,KOG1178@2759|Eukaryota,38V1T@33154|Opisthokonta,3Q08R@4751|Fungi,3R2AF@4890|Ascomycota,20DTP@147545|Eurotiomycetes,3AZS6@33183|Onygenales	4751|Fungi	Q	Condensation domain	-	-	-	ko:K22152	-	-	-	ko00000	-	-	-	AMP-binding,Condensation,PP-binding

> Your eggnog-mapper:
>#query_name	seed_eggNOG_ortholog	seed_ortholog_evalue	seed_ortholog_score	predicted_gene_name	GO_terms	KEGG_pathways	Annotation_tax_scope	OGs	bestOG|evalue|score	COG cat	eggNOG annot
mp040_13792	441959.XP_002479979.1	5.00E-71	232.2	FG02084.1	GO:0005575,GO:0005623,GO:0005886,GO:0006810,GO:0008150,GO:0015886,GO:0016020,GO:0016021,GO:0031224,GO:0044425,GO:0044464,GO:0044699,GO:0044765,GO:0051179,GO:0051181,GO:0051234,GO:0071702,GO:0071705,GO:0071944,GO:1901678		fuNOG[21]	03RFZ@ascNOG,0IWNB@euNOG,0M5FN@euroNOG,0MQ5B@eurotNOG,0PN5J@fuNOG,11Q0B@NOG,13QP8@opiNOG	0PN5J|7.70053432588e-86|288.860290527	S	RTA1 domain protein

Any guidance would be appreciated!

-Tania

**Comment by egluckthaler** [comment]
Hi Tania, excited to see what you find :) the emapper output included in the tutorial is from an older version that doesn't have the same columns as newer output. Basically, the goal in this step is to obtain a 3 column tsv file where col1=geneID, col2=orthogroupID, col3=orthogroupInfo
The following code should work on your emapper output
`cut -f1,5 ann/*emapper.annotations | grep -v '#' | perl -pe 's/(^.+?)\t.+,([^,]+)$/\1\t\2/' | perl -pe 's/@/\t/' > ann/macph6.gene2og.txt`

**Comment by tania-k** [comment]
Hi Emile, Thank you for that suggestion. I now see you had it as a suggestion below the step I was trying out. Apologies for not testing it out. Yes, it did work, now I am running eggnog annotations on the remainder of my Histoplasma genomes to get the same information out. 
I will let you know once I have progressed and hopefully with starship results!

**Comment by egluckthaler** [comment]
sounds great, good luck!
