### ISSUE TITLE
sh: 1: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by Mar-Gra-creator** [egluckthaler/starfish#6]
hey i do now what is wrong...

```
(starfish) marcin@marcin-:~/starfish/test$ starfish annotate -T 2 -x macpha6_tyr -a ome2assembly.txt -g ome2gff.txt -p ../db/YRsuperfams.p1-512.hmm -P ../db/YRsuperfamRefs.faa -i tyr -o geneFinder/
[Thu Apr 25 21:33:47 2024] executing command: starfish annotate -T 2 -x macpha6_tyr -a ome2assembly.txt -g ome2gff.txt -p ../db/YRsuperfams.p1-512.hmm -P ../db/YRsuperfamRefs.faa -i tyr -o geneFinder/
Key parameters:
metaeuk        -v 3 -s 7.5 -e 0.0001 --max-intron 2000 --max-seqs 300 --metaeuk-eval 0.001 --exhaustive-search 1 --metaeuk-tcov 0.25 --allow-deletion 1 --protein 1 --disk-space-limit 100G --compressed 1
hmmsearch      --max -E 0.001

[Thu Apr 25 21:33:47 2024] geneFinder//macpha6_tyr.fas exists, skipping metaeuk annotation
[Thu Apr 25 21:33:47 2024] geneFinder//macpha6_tyr.hmmout exists, skipping HMM annotation of metaeuk results
[Thu Apr 25 21:33:47 2024] filtering metaeuk annotations based on hmmsearch results..
[Thu Apr 25 21:33:47 2024] lifting over names of overlapping feature from GFFs in ome2gff.txt to metaeuk annotations..
[Thu Apr 25 21:33:47 2024] checking formatting of GFFs in ome2gff.txt..
sh: 1: Syntax error: "(" unexpected
```
cheers

**Comment by egluckthaler** [comment]
can you please post your ome2gff.txt file?

**Comment by ambikapokhrel** [comment]
Hi Emile,

I am also running into the similar problem. 

Code: starfish annotate -T 10 -x fusarium_tyr -a ome2assembly.txt -g ome2gff.txt -p $STARFISHDIR/db/YRsuperfams.p1-512.hmm -P $STARFISHDIR/db/YRsuperfamRefs.faa -i tyr -o geneFinder/


Thu May  2 22:11:42 2024] running metaeuk easy-predict for 24 assemblies..
[Thu May  2 22:37:59 2024] running hmmsearch on metaeuk annotations..
[Thu May  2 22:38:13 2024] filtering metaeuk annotations based on hmmsearch results..
[Thu May  2 22:38:13 2024] lifting over names of overlapping feature from GFFs in ome2gff.txt to metaeuk annotations..
[Thu May  2 22:38:13 2024] checking formatting of GFFs in ome2gff.txt..
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `bedtools intersect -a geneFinder//fusarium_tyr.filt.gff -b <(grep -w mRNA /scratch/aubrrb/TE/starship/gff3/F23_starfish.gff3) -wao >> geneFinder//fusarium_tyr.intersect.gff'


[Thu May  2 22:38:13 2024] error: could not execute bedtools intersect on commandline for geneFinder//fusarium_tyr.filt.gff and /scratch/aubrrb/TE/starship/gff3/F23_starfish.gff3, exiting..
No such file or directory


##my ome2gff.txt file 
22470   /scratch/aubrrb/TE/starship/gff3/22470_starfish.gff3
230306  /scratch/aubrrb/TE/starship/gff3/230306_starfish.gff3
F105    /scratch/aubrrb/TE/starship/gff3/F105_starfish.gff3
F109    /scratch/aubrrb/TE/starship/gff3/F109_starfish.gff3
F23     /scratch/aubrrb/TE/starship/gff3/F23_starfish.gff3
F79     /scratch/aubrrb/TE/starship/gff3/F79_starfish.gff3
HDV247  /scratch/aubrrb/TE/starship/gff3/HDV247_starfish.gff3
Necha3  /scratch/aubrrb/TE/starship/gff3/Necha3_starfish.gff3
T110    /scratch/aubrrb/TE/starship/gff3/T110_starfish.gff3
T126    /scratch/aubrrb/TE/starship/gff3/T126_starfish.gff3
T159    /scratch/aubrrb/TE/starship/gff3/T159_starfish.gff3
T161    /scratch/aubrrb/TE/starship/gff3/T161_starfish.gff3
T200    /scratch/aubrrb/TE/starship/gff3/T200_starfish.gff3
T219    /scratch/aubrrb/TE/starship/gff3/T219_starfish.gff3
T23     /scratch/aubrrb/TE/starship/gff3/T23_starfish.gff3
T299    /scratch/aubrrb/TE/starship/gff3/T299_starfish.gff3
T2      /scratch/aubrrb/TE/starship/gff3/T2_starfish.gff3
T31     /scratch/aubrrb/TE/starship/gff3/T31_starfish.gff3
T33     /scratch/aubrrb/TE/starship/gff3/T33_starfish.gff3
T36     /scratch/aubrrb/TE/starship/gff3/T36_starfish.gff3
T415    /scratch/aubrrb/TE/starship/gff3/T415_starfish.gff3
T77     /scratch/aubrrb/TE/starship/gff3/T77_starfish.gff3
T78     /scratch/aubrrb/TE/starship/gff3/T78_starfish.gff3
T95     /scratch/aubrrb/TE/starship/gff3/T95_starfish.gff3

**Comment by egluckthaler** [comment]
Hmm I cannot reproduce this error. Can you please download the latest version of starfish from conda and try again? If that doesn't work, can you please post the first 10 lines of the file  /scratch/aubrrb/TE/starship/gff3/F23_starfish.gff3? Can you also tell me what shell version you are using by typing the command: ```ps -p $$```

**Comment by ambikapokhrel** [comment]
I think I am using the latest version, I just downloaded and installed two days ago "starfish v1.0.0".

#First 10 lines of F23_starfish.gff3
F23_scaffold-1  prediction      mRNA    74835   75798   .       -       .       ID=F23_466;Name=F23_466
F23_scaffold-1  prediction      mRNA    121430  123050  .       -       .       ID=F23_552;Name=F23_552
F23_scaffold-1  prediction      mRNA    173851  175584  .       -       .       ID=F23_739;Name=F23_739
F23_scaffold-1  prediction      mRNA    227623  229074  .       -       .       ID=F23_871;Name=F23_871
F23_scaffold-1  prediction      mRNA    248379  249951  .       -       .       ID=F23_888;Name=F23_888
F23_scaffold-1  prediction      mRNA    248027  248378  .       +       .       ID=F23_889;Name=F23_889
F23_scaffold-1  prediction      mRNA    250289  252915  .       +       .       ID=F23_891;Name=F23_891
F23_scaffold-1  prediction      mRNA    327328  329502  .       +       .       ID=F23_1038;Name=F23_1038
F23_scaffold-1  prediction      mRNA    445554  447363  .       -       .       ID=F23_1319;Name=F23_1319
F23_scaffold-1  prediction      mRNA    540496  541377  .       -       .       ID=F23_1405;Name=F23_1405


#Shell version
GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu).

**Comment by egluckthaler** [comment]
Thank you. I think I fixed the problem. Please re-install starfish from conda (it should be version 1.0.1, you can check with the command ```starfish version```, and let me know if that works

**Comment by ambikapokhrel** [comment]
Thanks, Emile, it worked!

**Comment by egluckthaler** [comment]
Great, thanks!
