### ISSUE TITLE
Some questions about the parameter "-p" in starfish annotate module

### ISSUE THREAD

**Issue by 1835033964** [egluckthaler/starfish#7]
Hi! We encountered some difficulties while predicting the starship transposons.
The parameter "-p" is the profile HMM file in starfish annotate module. I wonder how can I obtain the HMM files when using the module? Which HMM file we shoud dowload when we  predict the starship transposons? Could we obtain the HMM files on some public database？ We would appreciate it if you could provide us with a web address for the database.

Thank you!

**Comment by egluckthaler** [comment]
Hello, you can find the relevant HMMs in the db/ directory in the github repository. The step-by-step tutorial in the github wiki page documents how to use the HMM file. if you are only interested in predicted tyrosine recombinases, you should use the [YRsuperfams.p1-512.hmm](https://github.com/egluckthaler/starfish/blob/main/db/YRsuperfams.p1-512.hmm) and its accompanying fasta file [YRsuperfamRefs.faa](https://github.com/egluckthaler/starfish/blob/main/db/YRsuperfamRefs.faa). thanks!

**Comment by 1835033964** [comment]
Thank you! I found the the HMM files in the db/ diretory .  And thanks for your reply for using the HMM files.
