### ISSUE TITLE
interpreting starfish insert error

### ISSUE THREAD

**Issue by metalichen** [egluckthaler/starfish#8]
Hi Emile,

Thanks for the great tool! I've been running it on a couple of genomes I'm working with. I followed your tutorial and was able to idenitify some tyr genes there. However, when I got to the element annotation step I got the following:

```
[Mon May 20 15:37:25 2024] executing command: starfish insert -T 2 -a analysis_and_temp_files/12_starship/ome2assembly.txt -d analysis_and_temp_files/12_starship/blastdb/macpha6.assemblies -b analysis_and_temp_files/12_starship/geneFinder/macpha6.tyr.bed -i tyr -x macpha6 -o analysis_and_temp_files/12_starship/elementFinder/
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Key parameters:
--upstream             0-17000
--downstream           0-14000
--length               2000-700000
--pid                  90
--hsp                  1000
minDR                  4
maxDR                  40
maxEmptySiteLength     2000
maxElementLengthFlag   700000
minElementLengthFlag   2000
maxInsertCoverage      0.25
maxFlankCoverage       0.25
blastn                 -task dc-megablast -evalue 0.0001 -max_target_seqs 1000000
nucmer                 --mum
delta-filt             -m -l 1000 -i 90

[Mon May 20 15:37:25 2024] reading in data..
[Mon May 20 15:37:25 2024] parsing upstream regions of 11 candidate tyr captains..
[Mon May 20 15:37:25 2024] searching for hits to the upstream regions of 11 candidate tyr captains..
[Mon May 20 15:37:37 2024] found 4 tyr captains with candidate insertion sites
[Mon May 20 15:37:37 2024] searching for hits to the downstream regions of candidate insertion sites for 4 tyr captains that are also downstream of those captains..
[Mon May 20 15:37:42 2024] filtering out similar upstream and downstream flanks of insertion sites associated with 0 candidate tyr captains..
[Mon May 20 15:37:43 2024] refining boundary predictions of 0 candidate tyr captains with insertion sites..
BLAST options error: File analysis_and_temp_files/12_starship/elementFinder//emptyDB.macpha6.fa is empty


[Mon May 20 15:37:43 2024] error: could not execute makeblastdb on commandline, exiting..
Inappropriate ioctl for device
```

Does this mean that the 4 tyr genes that had upstream candidate insertion sites didn't have downstream sites, and that caused the error? If so, could it be because of the assembly fragmentation? One of the assemblies I'm working with isn't very contiguos (~60 contigs), so I thought it might be a problem here. 

Thanks!
Gulnara

**Comment by egluckthaler** [comment]
Hi Gulnara, thanks! To answer your questions: yes and yes. I will update the program to provide a more interpretable error output, but essentially, none of the 4 tyrs had good evidence for a bonafide insertion site. the most common cause for this is indeed assembly fragmentation (although 60 contigs doesnt sound too bad). Another cause could be that given the individuals in your analysis, no segregating insertion site was found. if you have the opportunity to add more individuals from your target species to the analysis, I would try that because the more individuals from a specific species you include, the higher the chances of finding a segregating insertion site.

**Comment by metalichen** [comment]
Thanks, this makes sense! I have only one long-read genome assembly, but I have several short-read genomes from different individuals, each consisting of several hundreds contigs. Do you think it's worth trying including those, or are they too fragmented to be useful?

**Comment by egluckthaler** [comment]
I'd say its always worth a try

**Comment by metalichen** [comment]
Got it, thanks!
