### ISSUE TITLE
skimage_feature

### ISSUE THREAD

**Issue by BenAuxier** [egluckthaler/starfish#9]
Hi,

Just did a clean install of starfish, but I get an error at the annotate step:

`  File "/mnt/LTR_userdata/auxie001/programs/conda/envs/starfish/bin/starfish", line 7, in <module>`
`from starfish.core.starfish import starfish`
`File "/mnt/LTR_userdata/auxie001/programs/conda/envs/starfish/lib/python3.8/site-packages/starfish/__init__.py", line 1, in <module>`
`from . import (`
`File "/mnt/LTR_userdata/auxie001/programs/conda/envs/starfish/lib/python3.8/site-packages/starfish/image.py", line 1, in
<module>`
`from starfish.core.image import (  # noqa: F401`
`  File "/mnt/LTR_userdata/auxie001/programs/conda/envs/starfish/lib/python3.8/site-packages/starfish/core/image/__init__.py", line 2, in <module>`
`    from ._registration import LearnTransform`
`  File "/mnt/LTR_userdata/auxie001/programs/conda/envs/starfish/lib/python3.8/site-packages/starfish/core/image/_registration/LearnTransform/__init__.py", line 2, in <module>`
`    from .translation import Translation`
`  File "/mnt/LTR_userdata/auxie001/programs/conda/envs/starfish/lib/python3.8/site-packages/starfish/core/image/_registration/LearnTransform/translation.py", line 2, in <module>`
`    from skimage.feature import register_translation`
`ImportError: cannot import name 'register_translation' from 'skimage.feature' (/mnt/LTR_userdata/auxie001/programs/conda/envs/starfish/lib/python3.8/site-packages/skimage/feature/__init__.py)`

From the sci-kit image blog, [here](https://scikit-image.org/docs/stable/release_notes/release_0.19.html#scikit-image-0-19-0-2021-12-03) I think the feature register_translation has been removed as of v0.19.3, and now they suggest using skimage.registration.phase_cross_correlation()

**Comment by egluckthaler** [comment]
thanks for the heads up Ben. I'm going to look into this

**Comment by BenAuxier** [comment]
Ah, I see I cannot replicate it either. I did include gffread and seqtk in my install, so not totally clean. That might be a cause.  Now using a conda environment with only starfish inside doesn't seem to raise any issues.
